import type { AppProps } from "next/app";
import styled, { ThemeProvider } from "styled-components";
import Head from "next/head";
import themes from "../commons/themes";
import GlobalStyles from "../commons/GlobalStyles";

const Container = styled.main`
    max-width: 480px;
    background: ${themes.color.background};
    margin: 0 auto;
`;

const MyApp = ({ Component, pageProps }: AppProps) => {
    return (
        <ThemeProvider theme={themes}>
            <GlobalStyles />
            <Container>
                <Head>
                    <title>Illogical Love</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Component {...pageProps} />
            </Container>
        </ThemeProvider>
    );
};

export default MyApp;
